import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from "react-i18next";
function InfoRow({ label, children }) {
    return (_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-start gap-0.5 sm:gap-3 py-2.5 border-b border-stone-100 last:border-0", children: [_jsx("span", { className: "text-[11px] font-semibold uppercase tracking-wider text-stone-400 sm:w-28 shrink-0 pt-0.5", children: label }), _jsx("span", { className: "text-[13px] text-stone-700", children: children })] }));
}
export default function AboutPage() {
    const { i18n } = useTranslation();
    const isMn = (i18n.resolvedLanguage ?? i18n.language) === "mn";
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "mb-5", children: _jsx("h2", { className: "text-xl font-semibold text-stone-900", children: isMn ? "Бидний тухай" : "About Us" }) }), _jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsxs("div", { className: "flex items-center gap-3 mb-3", children: [_jsx("div", { className: "w-10 h-10 rounded-xl bg-stone-950 flex items-center justify-center shrink-0", children: _jsxs("svg", { width: "22", height: "22", viewBox: "0 0 48 48", fill: "none", "aria-hidden": "true", children: [_jsxs("defs", { children: [_jsxs("linearGradient", { id: "ag1", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "#d97706", stopOpacity: "0.25" }), _jsx("stop", { offset: "100%", stopColor: "#d97706", stopOpacity: "0.12" })] }), _jsxs("linearGradient", { id: "ag2", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "#d97706", stopOpacity: "0.65" }), _jsx("stop", { offset: "100%", stopColor: "#b45309", stopOpacity: "0.5" })] }), _jsxs("linearGradient", { id: "ag3", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "0%", stopColor: "#fbbf24" }), _jsx("stop", { offset: "100%", stopColor: "#92400e" })] })] }), _jsx("rect", { x: "4", y: "32", width: "10", height: "12", rx: "2.5", fill: "url(#ag1)" }), _jsx("rect", { x: "17", y: "22", width: "10", height: "22", rx: "2.5", fill: "url(#ag2)" }), _jsx("rect", { x: "30", y: "10", width: "10", height: "34", rx: "2.5", fill: "url(#ag3)" }), _jsx("circle", { cx: "35", cy: "7", r: "5.5", fill: "white", fillOpacity: "0.1" }), _jsx("path", { d: "M35 4.2L36.1 6.7H38.7L36.6 8.2L37.4 10.8L35 9.3L32.6 10.8L33.4 8.2L31.3 6.7H33.9Z", fill: "#fbbf24" })] }) }), _jsxs("div", { children: [_jsxs("p", { className: "text-[15px] font-bold text-stone-900", children: [_jsx("span", { children: "Champ" }), _jsx("span", { style: { background: "linear-gradient(135deg,#fbbf24 0%,#d97706 100%)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }, children: "Step" })] }), _jsx("p", { className: "text-[10px] text-stone-400 uppercase tracking-widest", children: "Digital Portfolio App" })] })] }), _jsx("p", { className: "text-[13px] text-stone-600 leading-relaxed", children: isMn
                            ? "ChampStep нь хүүхдийн амжилт, ур чадвар, өсөлтийг бүртгэж PDF портфолио үүсгэх монгол эцэг эх, багш нарт зориулсан дижитал апп юм."
                            : "ChampStep is a digital portfolio app for Mongolian parents and teachers to record children's achievements and export beautiful PDF portfolios." })] }), _jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsx("h3", { className: "text-[11px] font-semibold uppercase tracking-wider text-stone-400 mb-3", children: isMn ? "Байгууллагын мэдээлэл" : "Company Information" }), _jsxs("div", { children: [_jsx(InfoRow, { label: isMn ? "Нэр" : "Name", children: isMn ? '"Итгэлийн Шинэ Улирал" ХХК' : "New Season for Faith Co.,Ltd" }), _jsx(InfoRow, { label: isMn ? "Хаяг" : "Address", children: isMn
                                    ? "Улаанбаатар хот, Баянзүрх дүүрэг, 42-р хороо, 14-р хороолол, Алтан тэвш, 60б, 21 тоот"
                                    : "Altantevsh 60b apt 21, 14th khoroolol, 42nd khoroo, Bayanzurkh, Ulaanbaatar, Mongolia" }), _jsx(InfoRow, { label: isMn ? "Веб" : "Website", children: _jsx("a", { href: "https://www.champstep.mn", target: "_blank", rel: "noopener noreferrer", className: "text-amber-600 hover:underline", children: "www.champstep.mn" }) }), _jsx(InfoRow, { label: isMn ? "И-мэйл" : "Email", children: _jsx("a", { href: "mailto:info@champstep.mn", className: "text-amber-600 hover:underline", children: "info@champstep.mn" }) }), _jsx(InfoRow, { label: isMn ? "Утас" : "Phone", children: "+976 8998-3613" })] })] }), _jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsx("h3", { className: "text-[11px] font-semibold uppercase tracking-wider text-stone-400 mb-3", children: isMn ? "Үйлчилгээний мэдээлэл" : "Service Information" }), _jsxs("div", { children: [_jsx(InfoRow, { label: isMn ? "Төрөл" : "Type", children: isMn ? "Цахим захиалгат үйлчилгээ (SaaS)" : "Digital subscription service (SaaS)" }), _jsx(InfoRow, { label: isMn ? "Хүргэлт" : "Delivery", children: isMn
                                    ? "Тэр даруй — бүртгэлийн дараа шууд ашиглана"
                                    : "Instant — available immediately after signup" }), _jsx(InfoRow, { label: isMn ? "Төлбөр" : "Payment", children: isMn
                                    ? "Сарын захиалга — банкны картаар"
                                    : "Monthly subscription — paid by bank card" }), _jsx(InfoRow, { label: isMn ? "Картын мэдээлэл" : "Card data", children: isMn
                                    ? "Манай системд хадгалдаггүй — банкны gateway-ээр дамждаг"
                                    : "Not stored by us — processed by payment gateway" })] })] }), _jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsx("h3", { className: "text-[11px] font-semibold uppercase tracking-wider text-stone-400 mb-3", children: isMn ? "Үнийн жагсаалт" : "Pricing" }), _jsx("div", { className: "space-y-2", children: [
                            {
                                name: isMn ? "Үнэгүй" : "Free",
                                price: "₮0",
                                desc: isMn ? "1 хүүхэд · 30 бичлэг хүртэл" : "1 child · Up to 30 entries",
                            },
                            {
                                name: isMn ? "Гэр бүл" : "Family",
                                price: "₮9,900",
                                desc: isMn ? "3 хүүхэд · Хязгааргүй бичлэг · PDF" : "3 children · Unlimited entries · PDF",
                            },
                            {
                                name: isMn ? "Мастер" : "Master",
                                price: "₮24,900",
                                desc: isMn ? "10 хүүхэд · Хязгааргүй бичлэг · PDF · AI" : "10 children · Unlimited entries · PDF · AI",
                            },
                            {
                                name: isMn ? "Багш" : "Coach",
                                price: "₮49,900",
                                desc: isMn ? "30 хүүхэд · Хязгааргүй бичлэг · PDF · AI" : "30 children · Unlimited entries · PDF · AI",
                            },
                        ].map((tier) => (_jsxs("div", { className: "flex items-center justify-between py-2 border-b border-stone-100 last:border-0", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[13px] font-medium text-stone-800", children: tier.name }), _jsx("p", { className: "text-[11px] text-stone-400", children: tier.desc })] }), _jsxs("span", { className: "text-[13px] font-semibold text-amber-600", children: [tier.price, _jsx("span", { className: "text-[10px] text-stone-400 font-normal", children: isMn ? "/сар" : "/mo" })] })] }, tier.name))) })] }), _jsxs("div", { className: "bg-amber-50 rounded-2xl border border-amber-200 p-5", children: [_jsx("p", { className: "text-[13px] text-amber-800 leading-relaxed mb-3", children: isMn
                            ? "Асуулт, гомдол, санал хүсэлт байвал и-мэйл хаягаар бидэнтэй холбогдоно уу. 24 цагийн дотор хариу өгнө."
                            : "For questions, complaints, or feedback, please contact us by email. We respond within 24 hours." }), _jsxs("a", { href: "mailto:info@champstep.mn", className: "inline-flex items-center gap-1.5 text-[13px] font-semibold text-amber-700 hover:text-amber-900 transition-colors", children: [_jsx("svg", { className: "w-4 h-4", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 1.8, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" }) }), "info@champstep.mn"] })] }), _jsx("p", { className: "text-center text-[11px] text-stone-400 py-2", children: "\u00A9 2025 \u0418\u0442\u0433\u044D\u043B\u0438\u0439\u043D \u0428\u0438\u043D\u044D \u0423\u043B\u0438\u0440\u0430\u043B \u0425\u0425\u041A \u00B7 info@champstep.mn" })] }));
}
