import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useTranslation } from "react-i18next";
function Section({ title, children }) {
    return (_jsxs("div", { className: "mb-5", children: [_jsx("h3", { className: "text-[13px] font-semibold text-stone-800 mb-1.5", children: title }), _jsx("div", { className: "text-[13px] text-stone-600 leading-relaxed", children: children })] }));
}
export default function TermsPage() {
    const { i18n } = useTranslation();
    const isMn = (i18n.resolvedLanguage ?? i18n.language) === "mn";
    const [tab, setTab] = useState("terms");
    const tabs = [
        { id: "terms", label: isMn ? "Үйлчилгээний нөхцөл" : "Terms of Service" },
        { id: "refund", label: isMn ? "Буцаан олгох бодлого" : "Refund Policy" },
        { id: "privacy", label: isMn ? "Нууцлалын бодлого" : "Privacy Policy" },
    ];
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "mb-2", children: _jsx("h2", { className: "text-xl font-semibold text-stone-900", children: isMn ? "Нөхцөл" : "Terms" }) }), _jsx("div", { className: "bg-stone-100 rounded-xl p-1 flex gap-1", children: tabs.map((t) => (_jsx("button", { onClick: () => setTab(t.id), className: `flex-1 text-[11px] font-medium px-2 py-2 rounded-lg transition-all ${tab === t.id
                        ? "bg-white shadow-sm text-stone-900"
                        : "text-stone-500 hover:text-stone-700"}`, children: t.label }, t.id))) }), tab === "terms" && (_jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsx("p", { className: "text-[10px] text-stone-400 mb-4", children: isMn ? "Сүүлд шинэчлэгдсэн: 2025 оны 5-р сар" : "Last updated: May 2025" }), _jsx(Section, { title: isMn ? "1. Үйлчилгээний тухай" : "1. About the Service", children: isMn
                            ? 'ChampStep нь хүүхдийн амжилт бүртгэх цахим үйлчилгээ. "Итгэлийн Шинэ Улирал" ХХК-аас үзүүлдэг.'
                            : "ChampStep is a digital service for recording children's achievements, provided by New Season for Faith Co.,Ltd." }), _jsx(Section, { title: isMn ? "2. Бүртгэл ба хэрэглэгчийн эрх" : "2. Registration & User Rights", children: isMn
                            ? "И-мэйл хаягаараа бүртгүүлнэ. Бүртгүүлэхэд картын мэдээлэл шаардахгүй. Нууц үгээ хэзээ ч хуваалцаж болохгүй."
                            : "Register with your email. No card details required to register. Never share your password with others." }), _jsx(Section, { title: isMn ? "3. Захиалга ба төлбөр" : "3. Subscription & Payment", children: isMn
                            ? "Премиум захиалга сар бүр автоматаар шинэчлэгдэнэ. Цуцлаагүй бол дараа сарын эхэнд дахин төлбөр авна. Төлбөрийг банкны картаар авна."
                            : "Premium subscriptions renew automatically each month. Unless cancelled, you will be charged at the start of the next month. Payments are made by bank card." }), _jsx(Section, { title: isMn ? "4. Хориглох зүйл" : "4. Prohibited Activities", children: isMn
                            ? "Бусдын хувийн мэдээлэл оруулах, систем эвдэх, хуурамч бүртгэл үүсгэх, зохиогчийн эрх зөрчихийг хориглоно."
                            : "Prohibited: entering others' personal data, damaging the system, creating fake accounts, or copyright infringement." }), _jsx(Section, { title: isMn ? "5. Үйлчилгээний зогсолт" : "5. Service Termination", children: isMn
                            ? "Дүрэм зөрчсөн тохиолдолд урьдчилан мэдэгдэлгүйгээр бүртгэлийг хаах эрхтэй. Та өөрийн бүртгэлийг хүссэн үедээ устгаж болно."
                            : "We reserve the right to terminate accounts violating our rules without prior notice. You may delete your own account at any time." })] })), tab === "refund" && (_jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsx(Section, { title: isMn ? "1. Цуцлах нөхцөл" : "1. Cancellation Terms", children: isMn
                            ? "Захиалгаа хүссэн үедээ цуцалж болно. Цуцалсны дараа дараагийн тооцооны үеэс идэвхгүй болно. Одоогийн сарын хугацаа дуустал үйлчилгээ ашиглах боломжтой."
                            : "You may cancel your subscription at any time. Cancellation takes effect from the next billing cycle. You may continue using the service until the period ends." }), _jsx(Section, { title: isMn ? "2. Буцаан олгох нөхцөл" : "2. Refund Conditions", children: isMn
                            ? "Техникийн алдаанаас болж үйлчилгээ ашиглах боломжгүй болсон тохиолдолд 7 хоногийн дотор хүсэлт гаргавал буцааж олгоно. Хүсэлтийг info@champstep.mn руу илгээнэ."
                            : "If the service is unavailable due to technical errors, refunds are available within 7 days upon request. Send requests to info@champstep.mn." }), _jsx(Section, { title: isMn ? "3. Буцаан олгохгүй тохиолдол" : "3. Non-refundable Cases", children: isMn ? (_jsxs("ul", { className: "list-disc list-inside space-y-1", children: [_jsx("li", { children: "\u0417\u0430\u0445\u0438\u0430\u043B\u0433\u0430 \u0430\u0448\u0438\u0433\u043B\u0430\u0441\u043D\u044B \u0434\u0430\u0440\u0430\u0430 \u0446\u0443\u0446\u0430\u043B\u0441\u0430\u043D \u0442\u043E\u0445\u0438\u043E\u043B\u0434\u043E\u043B" }), _jsx("li", { children: "\u041D\u04E9\u0445\u0446\u04E9\u043B \u0437\u04E9\u0440\u0447\u0441\u04E9\u043D\u0438\u0439 \u0443\u043B\u043C\u0430\u0430\u0441 \u0431\u04AF\u0440\u0442\u0433\u044D\u043B \u0445\u0430\u0430\u0433\u0434\u0441\u0430\u043D \u0442\u043E\u0445\u0438\u043E\u043B\u0434\u043E\u043B" }), _jsx("li", { children: "\u0425\u044D\u0440\u044D\u0433\u043B\u044D\u0433\u0447\u0438\u0439\u043D \u0430\u043B\u0434\u0430\u0430\u043D\u0430\u0430\u0441 \u04AF\u04AF\u0434\u0441\u044D\u043D \u0430\u0441\u0443\u0443\u0434\u0430\u043B" })] })) : (_jsxs("ul", { className: "list-disc list-inside space-y-1", children: [_jsx("li", { children: "Cancellation after using the subscription" }), _jsx("li", { children: "Account terminated due to policy violations" }), _jsx("li", { children: "Issues caused by user error" })] })) }), _jsx(Section, { title: isMn ? "4. Буцаан олгох хугацаа" : "4. Refund Timeline", children: isMn
                            ? "Хүсэлтийг 3–5 ажлын өдрийн дотор шийдвэрлэнэ. Мөнгийг банкны дансанд 7–14 ажлын өдрийн дотор буцаана."
                            : "Requests are processed within 3–5 business days. Funds are returned to your bank account within 7–14 business days." }), _jsxs("div", { className: "bg-amber-50 rounded-xl border border-amber-200 p-4 mt-2", children: [_jsx("p", { className: "text-[12px] text-amber-800 mb-2", children: isMn ? "Буцаан олгох хүсэлт илгээх:" : "Submit a refund request:" }), _jsx("a", { href: "mailto:info@champstep.mn", className: "text-[13px] font-semibold text-amber-700 hover:underline", children: "info@champstep.mn" })] })] })), tab === "privacy" && (_jsxs("div", { className: "bg-white rounded-2xl border border-stone-200 shadow-sm p-5", children: [_jsx(Section, { title: isMn ? "1. Цуглуулдаг мэдээлэл" : "1. Data We Collect", children: isMn
                            ? "И-мэйл хаяг, нэр, хүүхдийн амжилтын мэдээлэл. Картын мэдээлэл манай системд хадгалагддаггүй — банкны системээр дамждаг."
                            : "Email address, name, and children's achievement data. Card information is NOT stored in our system — it passes through the bank's payment system." }), _jsx(Section, { title: isMn ? "2. Мэдээллийг хэрхэн ашиглах" : "2. How We Use Your Data", children: isMn
                            ? "Зөвхөн үйлчилгээ үзүүлэх, захиалга удирдах, техникийн дэмжлэг үзүүлэх зорилгоор ашиглана. Гуравдагч этгээдэд зардаггүй, дамжуулдаггүй."
                            : "Used only to provide the service, manage subscriptions, and offer technical support. Never sold or transferred to third parties." }), _jsx(Section, { title: isMn ? "3. Мэдээллийн аюулгүй байдал" : "3. Data Security", children: isMn
                            ? "Бүх мэдээлэл Firebase дээр SSL шифрлэлттэй хадгалагдана. Нэвтрэх эрхийг Firebase Authentication удирддаг."
                            : "All data is stored on Firebase with SSL encryption. Access is managed by Firebase Authentication." })] })), _jsx("p", { className: "text-center text-[11px] text-stone-400 py-2", children: "\u00A9 2025 \u0418\u0442\u0433\u044D\u043B\u0438\u0439\u043D \u0428\u0438\u043D\u044D \u0423\u043B\u0438\u0440\u0430\u043B \u0425\u0425\u041A \u00B7 info@champstep.mn" })] }));
}
